" Transform 8 tab's into 4 wide tabs
set shiftwidth=4

" Autoindent if filetype supports it
set smartindent
set autoindent

set nowrap

" Show numbers in gutter
set number

" Set horizontal line
set cursorcolumn 
" Set vertical line
set cursorline 

" Improve search
set hlsearch
set incsearch

syntax on
colorscheme pablo

map ; :

" Change split
set splitbelow splitright
" Newtab
nnoremap <silent> <C-t> :tabnew<CR>
" Switch between tabs
nnoremap <Tab> gt
nnoremap <S-Tab> gT
" Disable arrow keys in all modes
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
