#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor ^1 -d 1 2 3 4 5 6 7 8 9


bspc config border_width          1
bspc config window_gap            1

bspc config split_ratio           0.50

bspc config borderless_monocle    true
bspc config single_monocle        true
bspc config gapless_monocle       false

# Focus on hover
bspc config focus_follows_pointer true

# Set pointer from X to pointer
xsetroot -cursor_name left_ptr

# Set border colors
bspc config normal_border_color   "#4c566a"
bspc config active_border_color   "#1e1e1e"
bspc config focused_border_color  "#E06C75"
bspc config presel_feedback_color "#5e81ac"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
